name: happy_liver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.12.2

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8

    # UI / media
    flutter_svg: ^2.3.0
    video_player: ^2.14.0

    # Firebase
    firebase_core: ^4.13.0
    firebase_auth: ^6.5.7
    cloud_firestore: ^6.8.0
    firebase_storage: ^13.5.0

    # Authentication
    google_sign_in: ^7.2.0

    # Local storage
    shared_preferences: ^2.5.5
    http: ^1.6.0
    image_picker: ^1.2.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/icons/
        - assets/videos/march_in_place.mp4
        - assets/icons/google.svg
        - assets/icons/apple.svg
        - assets/icons/arrow.svg
        - assets/images/logo.png
        - assets/images/book.png
        - assets/images/bulb.png
        - assets/videos/cholesterol.mp4
        - assets/videos/fatty_liver.mp4
        - assets/images/fatty_liver_thumbnail.png
        - assets/images/cholesterol_thumbnail.png
        - assets/images/back_arrow.png
        - assets/images/hourglass.png