// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO43j8_7xULChdRdH0AX5Cjpqpjw8K2gc',
    appId: '1:208141816996:web:299ec02b7c5a1bd6f48231',
    messagingSenderId: '208141816996',
    projectId: 'happy-liver-804af',
    authDomain: 'happy-liver-804af.firebaseapp.com',
    storageBucket: 'happy-liver-804af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD65j6QyOkqV_b_A-i5aI5cRiO2dBuwbM',
    appId: '1:208141816996:android:67b066c14e783fa5f48231',
    messagingSenderId: '208141816996',
    projectId: 'happy-liver-804af',
    storageBucket: 'happy-liver-804af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq6OItVjcWxwT4pfO75oPlK_IUEXH7IKY',
    appId: '1:208141816996:ios:6a28bbcb40d1512af48231',
    messagingSenderId: '208141816996',
    projectId: 'happy-liver-804af',
    storageBucket: 'happy-liver-804af.firebasestorage.app',
    androidClientId: '208141816996-sg6amr3e5cctumqai6hqgaa44dv3s1pj.apps.googleusercontent.com',
    iosClientId: '208141816996-tjof6upa582j8e19i1hlc43vvugbvs6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyLiverGit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq6OItVjcWxwT4pfO75oPlK_IUEXH7IKY',
    appId: '1:208141816996:ios:6a28bbcb40d1512af48231',
    messagingSenderId: '208141816996',
    projectId: 'happy-liver-804af',
    storageBucket: 'happy-liver-804af.firebasestorage.app',
    androidClientId: '208141816996-sg6amr3e5cctumqai6hqgaa44dv3s1pj.apps.googleusercontent.com',
    iosClientId: '208141816996-tjof6upa582j8e19i1hlc43vvugbvs6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyLiverGit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO43j8_7xULChdRdH0AX5Cjpqpjw8K2gc',
    appId: '1:208141816996:web:56e07cd61e1cc32af48231',
    messagingSenderId: '208141816996',
    projectId: 'happy-liver-804af',
    authDomain: 'happy-liver-804af.firebaseapp.com',
    storageBucket: 'happy-liver-804af.firebasestorage.app',
  );
}
