// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0TX79tyUyJC5_ZFfgEXMut1sYeEBBbLg',
    appId: '1:833014462788:web:c5c8c944cfe43d6085ff11',
    messagingSenderId: '833014462788',
    projectId: 'happy-liver-109cf',
    authDomain: 'happy-liver-109cf.firebaseapp.com',
    storageBucket: 'happy-liver-109cf.firebasestorage.app',
    measurementId: 'G-FR2KR6382V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJO77n4NkookVeas6Q9WM0_Td2ipE2DV0',
    appId: '1:833014462788:android:ec6ae8faaede472485ff11',
    messagingSenderId: '833014462788',
    projectId: 'happy-liver-109cf',
    storageBucket: 'happy-liver-109cf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsy6WLbIjDqFuEirn9KN-6du2vxrAF4eI',
    appId: '1:833014462788:ios:0c4cbf2faf95d18385ff11',
    messagingSenderId: '833014462788',
    projectId: 'happy-liver-109cf',
    storageBucket: 'happy-liver-109cf.firebasestorage.app',
    iosBundleId: 'com.example.happyLiver',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsy6WLbIjDqFuEirn9KN-6du2vxrAF4eI',
    appId: '1:833014462788:ios:0c4cbf2faf95d18385ff11',
    messagingSenderId: '833014462788',
    projectId: 'happy-liver-109cf',
    storageBucket: 'happy-liver-109cf.firebasestorage.app',
    iosBundleId: 'com.example.happyLiver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0TX79tyUyJC5_ZFfgEXMut1sYeEBBbLg',
    appId: '1:833014462788:web:49e5b24a01a2932585ff11',
    messagingSenderId: '833014462788',
    projectId: 'happy-liver-109cf',
    authDomain: 'happy-liver-109cf.firebaseapp.com',
    storageBucket: 'happy-liver-109cf.firebasestorage.app',
    measurementId: 'G-K9KGK8H8J9',
  );
}
